chat_app/urls.py
from django.urls import path
from chat_app import views

app_name = "chat_app"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('chat_room/', views.chat_room, name='chat_room'),
    path('send_message/', views.send_message, name='send_message'),
]

follow_user/follow_user_api/urls.py
from django.urls import path
from .import views

app_name = "follow_user.follow_user_api"

urlpatterns = [
    path('', views.CheckAPI.as_view(), name="check"),
    path('user/', views.AllUserView.as_view(), name="user"),
    path('notification/', views.NotificationView.as_view(), name="notification"),
    path('update_status/', views.UpdateStatusView.as_view(), name="update_status"),
    path('start_following/', views.StartFollowing.as_view(), name="start_following"),
    path('requestdelete/<int:pk>/', views.Requestdelete.as_view(), name="requestdelete"),
    path('profile_update/<int:pk>/', views.ProfileUpdateView.as_view(), name="profile_update"),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name="profile"),
]

follow_user/urls.py
from django.urls import path
from follow_user import views

app_name = "follow_user"

urlpatterns = [
    path('', views.home, name="home"),
    path('user/', views.AllUser.as_view(), name='user'),
    path('update_status/', views.update_status, name='update_status'),
    path('notification/', views.Notification.as_view(), name='notification'),
    path('following/', views.start_following, name='following'),
    path('delete_request/<int:pk>/',views.Requestdelete.as_view(), name='delete_request'),
    path('profile-update/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', views.profile,name='profile'),
    path('see_user_profile/', views.SeeUserProfileView.as_view(), name='see_user_profile'),
    path('changepassword/', views.changepassword,name='changepassword'),

]

post_app/urls.py
from django.urls import path
from . import views

app_name = "post_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('list_post/', views.ListPostView.as_view(), name='list_post'),
    path('create_post/', views.createpostview, name='create_post'),
    path('comment_post/', views.CreateCommentView.as_view(), name='comment_post'),
    path('delete_post/<int:pk>/', views.PostDelete.as_view(), name='delete_post'),
    path('like_post/', views.LikePostView.as_view(), name='like_post'),
    path('sort_like/', views.PostSortView.as_view(), name='sort_like'),
]

project_instagram/urls.py
from django.contrib import admin
from django.urls import path, include ,re_path
from django.conf import settings
from django.conf.urls.static import static
# from chat_app import routing

urlpatterns = [
    # re_path(r'^', include(routing)),
    path('', include('django_prometheus.urls')),

    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('follow_user/', include('follow_user.urls')),
    path('chat_app/', include('chat_app.urls')),
    path('post_app/', include('post_app.urls')),
    path('chatting_app/', include('chatting_app.urls')),
    path('api/', include('follow_user.follow_user_api.urls')),
    path('api_post/', include('post_app.post_api.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

follow_user/follow_user_api/models.py
from django.db import models

# Create your models here.

follow_user/models.py
from django.db import models
from user_app.models import User

# Create your models here.

class SendRequest(models.Model):

    STATUS_TYPE_CHOICES = (
        ('Follow', 'follow'),
        ('Following', 'following'),
        ('Requested', 'requested'),
        ('Confirm', 'confirm'),
        ('Delete', 'delete'),
        ('Accept', 'accept')
    )
    status = models.CharField(
        max_length=20, choices=STATUS_TYPE_CHOICES, null=True, default='Follow')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='send', null=True)
    current_time = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='request_user', null=True)
    receive = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='receive', null=True)
    
    def __str__(self):
        return self.user.email



    def save(self, *args, **kwargs):
        if self.sender:
            self.status = SendRequest.STATUS_TYPE_CHOICES[2][0]
        elif self.receive:
            self.status = SendRequest.STATUS_TYPE_CHOICES[3][0]
        super().save(*args, **kwargs)

   

follow_user/forms.py
from django import forms
from user_app. models import User


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields = ("images","email","first_name","last_name")

follow_user/follow_user_api/views.py
from rest_framework .views import APIView
from rest_framework.response import Response
from rest_framework.generics import ListAPIView , DestroyAPIView , UpdateAPIView , RetrieveAPIView
from user_app. models import User
from .serializer import AllUserSerializer , NotificationSerializer , RequestDeleteSerializer ,ProfileUpdateSerializer,ProfileSerializer
from follow_user.models import SendRequest 
from django.db.models import Q


# Create your views here.

class CheckAPI(APIView):
    def get(self,request):
        return Response("check......")
        

class AllUserView(ListAPIView):
    # http://localhost:8000/api/user/
    queryset = User.objects.all()
    serializer_class = AllUserSerializer

    def get_queryset(self):
        queryset = User.objects.filter(
            ~Q(is_staff=True) , ~Q(email=self.request.user))
        
        followed_users = SendRequest.objects.filter(
            user=self.request.user).values_list('sender__email', flat=True).last()

        if followed_users:
            queryset = queryset.exclude(email = followed_users )
            return queryset
        return queryset


class NotificationView(ListAPIView):
    # localhost:8000/api/notification/
    queryset = SendRequest.objects.all()
    serializer_class = NotificationSerializer

    def get_queryset(self):
        queryset = SendRequest.objects.filter(user=self.request.user)
        return queryset


class UpdateStatusView(APIView):
    # http://localhost:8000/api/update_status/?user=6
    def get(self,request):
        user_id = self.request.GET.get("user")
        user = User.objects.get(id=user_id)
        users = SendRequest.objects.create(user=user, receive=self.request.user)
        users = SendRequest.objects.create(user=self.request.user, sender=user)
        return Response("Successfully update status")


class StartFollowing(APIView):
    # localhost:8000/api/start_following/?receive=99   
    def get(self,request):
        receive = request.GET.get("receive")

        # Update the status of the opposite user to "Following"
        receive_email= SendRequest.objects.filter(id= receive).values_list('receive__email',flat=True)
        update_opposite_user = SendRequest.objects.filter(user__email__in = receive_email , status = "Requested" , sender = request.user).update(
            status=SendRequest.STATUS_TYPE_CHOICES[1][0])
    
        # Update the status of the current user to "Accept"
        update_current_user = SendRequest.objects.filter(id=receive).update(status=SendRequest.STATUS_TYPE_CHOICES[5][0])
        return Response("Start Following")


class Requestdelete(DestroyAPIView):
    # localhost:8000/api/requestdelete/103/   
    queryset = SendRequest
    serializer_class = RequestDeleteSerializer

    def get_object(self):
        user_id = self.kwargs['pk']
        del_request_id = SendRequest.objects.filter(id=user_id).values_list('receive')
        sender_del = SendRequest.objects.filter(user__in=del_request_id, status="Requested", sender__email=self.request.user.email)
        sender_del.delete()
        return super().get_object()


class ProfileUpdateView(UpdateAPIView):
    #PATCH - localhost:8000/api/profile_update/7/
    queryset = User
    serializer_class = ProfileUpdateSerializer


class ProfileView(RetrieveAPIView):
    # GET - localhost:8000/api/profile/9
    queryset = User.objects.all()
    serializer_class = ProfileSerializer

follow_user/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic.list import ListView
from project_instagram import settings
from user_app.models import User
from django.http import HttpResponse
from django.contrib.auth.hashers import check_password
from .forms import UserProfileUpdateForm
from follow_user .models import SendRequest


# Create your views here.

def home(request):
    return render(request, "f_base.html")

class AllUser(ListView):
    model = User
    context_object_name = "users"
    template_name = "all_user.html"

    def get_queryset(self):
        users = User.objects.filter(
            ~Q(is_staff=True), ~Q(email=self.request.user))

        followed_users = SendRequest.objects.filter(
            user=self.request.user).values_list('sender__email', flat=True)

        if followed_users:
            users = users.filter(~Q(send__user__email__in=followed_users))
            return users
        return users


class Notification(ListView):
    model = SendRequest
    context_object_name = "users"
    template_name = "notifications.html"

    def get_queryset(self):
        users = SendRequest.objects.filter(user=self.request.user)
        return users


def update_status(request):
    user_id = request.GET.get("user")
    user = User.objects.get(id=user_id)
    users = SendRequest.objects.create(user=user, receive=request.user)
    users = SendRequest.objects.create(user=request.user, sender=user)
    return redirect('follow_user:user')


def start_following(request):
    receive_id = request.GET.get("receive")

    # Update the status of the opposite user to "Following"
    receive_email= SendRequest.objects.filter(id= receive_id).values_list('receive__email',flat=True)
    update_opposite_user = SendRequest.objects.filter(user__email__in = receive_email , status = "Requested" , sender = request.user).update(
        status=SendRequest.STATUS_TYPE_CHOICES[1][0])
    
        # Update the status of the current user to "Accept"
    update_current_user = SendRequest.objects.filter(id=receive_id).update(status=SendRequest.STATUS_TYPE_CHOICES[5][0])
    return redirect("follow_user:user")


class Requestdelete(DeleteView):
    model = SendRequest
    template_name = "request_delete.html"
    success_url = reverse_lazy("follow_user:notification")

    def get_object(self):
        user_id = self.kwargs['pk']
        del_request_id = SendRequest.objects.filter(id=user_id).values_list('receive')
        sender_del = SendRequest.objects.filter(user__in=del_request_id, status="Requested", sender__email=self.request.user.email)
        sender_del.delete()
        return super().get_object()


# --------------------------------------------------------------------------------------------

def profile(request):
    return render(request, 'profile.html')


class ProfileUpdateView(LoginRequiredMixin,SuccessMessageMixin, UpdateView):
    login_url = settings.login_url
    form_class = UserProfileUpdateForm
    model = User
    template_name = 'profile-update.html'
    success_url = reverse_lazy("follow_user:profile")
    success_message = "Successfully Edit Profile..."


class SeeUserProfileView(ListView):
    model  = User
    context_object_name = "profile"
    template_name = "see_user_profile.html"
    
    def get_queryset(self):
        user_id =  self.request.GET.get("user")
        return User.objects.get(id=user_id)

# -----------------------------------------------------------------------
  
def changepassword(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        new_password = request.POST.get("new_password")
        try:
            user = User.objects.get(email=email)
            if check_password(password, user.password):
                user.set_password(new_password)
                user.save()
                return render(request, "changepasswords.html", {"message": "Successfully Changed Password"})
            else:
                return render(request, "changepasswords.html", {"message": "Incorrect Password"})
        except User.DoesNotExist:
            return render(request, "changepasswords.html", {"message": "User Does Not Exist"})
    else:
        return render(request, "changepasswords.html")

follow_user/templates/all_user.html
{% extends 'f_base.html' %}
{% load user_filters %}
{% load static %}


{% block content %}

<div style = "background-color:blanchedalmond; height:max-content" ><br><br>
  <table class="table-auto mx-auto w-full mt-8 border-collapse">
      <thead style="background-color:rgb(34, 34, 74); color:white">
        <tr  class="uppercase font-semibold text-sm">
          <th class="border border-black px-4 py-2"></th>
          <th class="border border-black px-4 py-2">Email</th>
          <th class="border border-black px-4 py-2">Name</th>
          <th class="border border-black px-4 py-2">Status</th>
        </tr>
      </thead>
      <tbody>

        {% for user in users %}
        <tr style="background-color:rgb(191, 203, 208);color:blue;">
        <td>
          {% if user.images %}
            <img class="card-img-top" src="{{user.images.url}}" style="width:100px; height: 100px;"alt="Card image cap">
          {% else %}
          <img src="{% static 'images/profile88.png' %}" class="rounded float-right" height="100px" width="100px">
          {% endif %}
        </td>


          <td class="border border-blue-900 px-4 py-2">
            <a href="/follow_user/see_user_profile/?user={{user.id}}">{{ user.email }}</a>
          </td>

          <td class="border border-blue-900 px-4 py-2">{{user.first_name}}</td>
          <td style="text-align: center;">
            <a href="/follow_user/update_status/?user={{ user.id }}"><button type="button" class="btn btn-primary" >Follow</button></a>
          </td> 
        </tr> 	
        {% endfor %}

       </tbody>
  </table>
</div>
{% endblock %}

follow_user/templates/changepasswords.html
{% extends 'f_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<center> 

{% if message %}
<div>{{ message}}</div>
{% endif %}

<br><br>

<form method="POST" action="" >
{% csrf_token %}

<h4>Change Password</h4>  <br<br><br>

<label>Email : </label>
<!-- <input type="text" name="email"> <br><br> -->
<!-- <input type="text" value="Default Value"> -->
<input type="text" name="email" value="{{request.user.email }}" readonly>   <br><br>


<label>Password : </label>
<input type="text" name="password">  <br><br>

<label>New Password : </label>
<input type="text" name="new_password">  <br><br>

<input type="submit" value="Change Password" >
</form>

</center>

{% endblock %}

follow_user/templates/comment.html
{% extends 'f_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div>
<center>

<div style="background-color: bisque;">
{% if messages %}
{% for message in messages %}
<div>{{ message}}</div>
{% endfor %}
{% endif %}
    
<div style="color:black;">
    <form action="" method="POST" enctype="multipart/form-data" style="width: 300px;">
        {% csrf_token %}
        <br><br>
        <h6><strong>Comment Here</strong> </h6> <br>
        {{form|crispy}}  <br>
        <button type="submit" class="btn btn-danger">Save</button> <br>
    </form>
</div>
</div>  

<br><br>

<div>
    {% for comment in post_message %}
    {% if request.user == comment.user %}
    <h6>{{request.user.first_name}} {{request.user.last_name}}</h6>
    {% else %}
    <h6>{{ comment.user }}</h6>
    {% endif %}

    <div style="color:black;">{{ comment.message }}</div>
    {% endfor %}
</div>
</center>
</div>
    
{% endblock %}

follow_user/templates/f_base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
    nav .navbar-nav li a {
      color: white !important;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg  bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand " href="#">Welcome</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item active">
            <h5 style="font-style:oblique;"><a class="nav-link active" aria-current="page" href="{% url 'post_app:list_post' %}">Home</a></h5>
          </li>

          <li class="nav-item">
            <h5><a class="nav-link" href="{% url 'follow_user:user' %}">Suggetion</a></h5>
          </li>

          <li class="nav-item">
            <h5><a class="nav-link" href="{% url 'follow_user:notification' %}">Notification</a></h5>
          </li>

          <li class="nav-item">
            <h5><a class="nav-link" href="{% url 'follow_user:profile' %}">Edit Profile</a></h5>
          </li>

          <li class="nav-item">
            <h5><a class="nav-link" href="{% url 'follow_user:changepassword' %}">Change Password</a></h5>
          </li>

          <!-- <li class="nav-item">
            <form method="GET" action="{% url 'post_app:sort_like' %}">
              <div class="input-group">
              <select class="custom-select" name="sort" id="sort" aria-label="Example select with button addon">   
                <option selected>-----</option>
                <option selected name="sort" value="LTH">Low to High</option>
                <option name="sort" value="HTL">High to Low</option>
              </select>
              <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="submit">Filter Likes</button>
            </div>
            </form>
          </li> -->
          
          <li class="nav-item">
            <h5> <a class="nav-link" href="/">Logout</a></h5>
          </li>

          <li class="nav-item">

            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </li>
        </ul>
        
        <li class="nav-item">
          <h5> <a class="nav-link" >{{request.user}}</h5>
        </li>
          

      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %} <br>


 
</body>

</html>


<!-- =======End New Footer ======= -->

follow_user/templates/notifications.html
{% extends 'f_base.html' %}
{% block content %}
{% load static %}

<div style="background-color: blanchedalmond; height: max-content"><br><br>

    <table class="table-auto mx-auto w-full mt-8 border-collapse">
      <thead style="background-color: rgb(34, 34, 74); color: white">
        <tr class="uppercase font-semibold text-sm">
          <th class="border border-black px-4 py-2">Image</th>
          <th class="border border-black px-4 py-2">Email</th>
          <th class="border border-black px-4 py-2">Status</th>
      </thead>

      <tbody>
      {% for user in users %}
        {% if user.status != "Accept" %}
        <tr style="background-color: gray; color: white;">
          <td>
            {% if user.sender and user.sender.images %}
            <img  class="card-img-top" src="{{ user.sender.images.url }}"  style="width:100px; height: 100px;"alt="Card image cap">
            
            {% elif user.receive and user.receive.images %}
            <img  class="card-img-top" src="{{ user.receive.images.url }}"  style="width:100px; height: 100px;"alt="Card image cap">

            {% else %}
            <img src="{% static 'images/profile95.png' %}" class="rounded float-right" height="100px" width="100px">
            {% endif %}
          </td>

          {% if user.sender %}
          <td class="border border-blue-900 px-4 py-2">{{ user.sender }}</td>
          {% elif user.receive %}
          <td class="border border-blue-900 px-4 py-2">{{ user.receive }}</td>
          {% endif %}
          
          {% if user.status == "Confirm" %}
          <td style="text-align: center;">
          <a href="/follow_user/following/?receive={{ user.id }}"><button type="button" class="btn btn-warning">{{ user.status }}</button></a>
          <a href="{% url 'follow_user:delete_request' user.id %}"><button type="button" class="btn btn-warning">Delete</button></a>
          </td>
          {% else %}
          <td style="text-align: center;"><button type="button" class="btn btn-warning">{{ user.status }}</button></td>
          {% endif %}
        </tr> 
        {% endif %}

        {% endfor %}
      </tbody>
    </table>
</div>

{% endblock %}

follow_user/templates/profile-update.html
{% extends 'f_base.html' %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />

{% block content %}
<div style="background-color: bisque; height:max-content">

    <center> <br>
        <h2>Update Profile</h2>
        <form method="POST" enctype="multipart/form-data" style="width:450px; height:500px;">
            {% csrf_token %}
            {{form | crispy}} <br>
            <button type="submit" class="btn btn-danger">Update</button>
        </form>
    </center>
</div>
{% endblock %}

follow_user/templates/profile.html
{% extends 'f_base.html' %}
{% load static %}
{% load user_filters %}


{% block content %}

{% if messages %}
{% for message in messages %}
<div class="text-center alert alert-{{ message.tags }} alert-dismissible">
  {{ message|safe }}
</div>
{% endfor %}
{% endif %}



<h5>Posts : {{user.id|get_no_post}}  &nbsp;&nbsp;&nbsp; Followers: {{ user.id|get_no_of_follower }} &nbsp;&nbsp;&nbsp; Following: {{ user.id|get_no_of_following }}</h5>

<center>
<div class="container-fluid">

  <h1 class="h3 mb-0 text-gray-800">Profile</h1>    <br><br>

  <!-- Main Content Here -->
  <div class="row">
    <div>
      {% if user.images %}
      <img src="{{user.images.url}}" class="rounded float-right" height="300px" width="300px">
      {% else %}
      <img src="{% static 'images/profile.png' %}" class="rounded float-right" height="300px" width="300px">
      {% endif %}
    </div>
    <div>
      <div class="card-body">
        <p><strong>Email: </strong> {{user.email}} </p>
        <p><strong>First Name : </strong> {{user.first_name}} </p>
        <p><strong>Last Name : </strong> {{user.last_name}} </p>

        <a href="{% url 'follow_user:profile-update' request.user.id %}" class="btn btn-sm btn-primary shadow-sm">Update
          Profile</a>
      </div>
    </div>
  </div>
</div>
</center>
{% endblock %}

follow_user/templates/request_delete.html
{% extends 'f_base.html' %}

{% block content %}

<div style="background-color:blanchedalmond;height:500px;">
   
    <center><br><br><br><br>

        <form method="POST">
            {% csrf_token %}

            <p>Are you sure you want to delete ?</p>
            {{form}}

            <input type="submit" value="Confirm">
        </form>
    </center>
</div>

{% endblock %}

follow_user/templates/see_user_profile.html
{% extends 'f_base.html' %}
{% load static %}
{% load user_filters %}


{% block content %}

{% if messages %}
{% for message in messages %}
<div class="text-center alert alert-{{ message.tags }} alert-dismissible">
  {{ message|safe }}
</div>
{% endfor %}
{% endif %}

<h5>Posts : {{profile.id|get_no_post}}  &nbsp;&nbsp;&nbsp; Followers: {{ profile.id|get_no_of_follower }} &nbsp;&nbsp;&nbsp; Following: {{ profile.id|get_no_of_following }}</h5>

<center>
<div class="container-fluid">

  <h1 class="h3 mb-0 text-gray-800">Profile</h1>    <br><br>

  <!-- Main Content Here -->
  <div class="row">
    <div>
      {% if profile.images %}
      <img src="{{profile.images.url}}" class="rounded float-right" height="300px" width="300px">
      {% else %}
      <img src="{% static 'images/avtar.png' %}" class="rounded float-right" height="300px" width="300px">
      {% endif %}
    </div>

    <div>
      <div class="card-body">
        <p><strong>Email: </strong> {{profile.email}} </p>
        <p><strong>First Name : </strong> {{profile.first_name}} </p>
        <p><strong>Last Name : </strong> {{profile.last_name}} </p>
      </div>
    </div>
  </div>
</div>
</center>
{% endblock %}