chat_app/urls.py
from django.urls import path
from chat_app import views

app_name = "chat_app"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('chat_room/', views.chat_room, name='chat_room'),
    path('send_message/', views.send_message, name='send_message'),
]

post_app/post_api/urls.py
from django.urls import path
from .import views

app_name = "post_app.post_api"

urlpatterns = [
    path('', views.CheckPostAPI.as_view(), name="post_check"),
    path('list_post/', views.ListPostView.as_view(), name="list_post"),
    path('create_post/', views.CreatePostview.as_view(), name="create_post"),
    path('like_post/', views.LikePostView.as_view(), name="like_post"),

]

post_app/urls.py
from django.urls import path
from . import views

app_name = "post_app"

urlpatterns = [
    path('', views.home, name="home"),
    path('list_post/', views.ListPostView.as_view(), name='list_post'),
    path('create_post/', views.createpostview, name='create_post'),
    path('comment_post/', views.CreateCommentView.as_view(), name='comment_post'),
    path('delete_post/<int:pk>/', views.PostDelete.as_view(), name='delete_post'),
    path('like_post/', views.LikePostView.as_view(), name='like_post'),
    path('sort_like/', views.PostSortView.as_view(), name='sort_like'),
]

project_instagram/urls.py
from django.contrib import admin
from django.urls import path, include ,re_path
from django.conf import settings
from django.conf.urls.static import static
# from chat_app import routing

urlpatterns = [
    # re_path(r'^', include(routing)),
    path('', include('django_prometheus.urls')),

    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('follow_user/', include('follow_user.urls')),
    path('chat_app/', include('chat_app.urls')),
    path('post_app/', include('post_app.urls')),
    path('chatting_app/', include('chatting_app.urls')),
    path('api/', include('follow_user.follow_user_api.urls')),
    path('api_post/', include('post_app.post_api.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post_app/models.py
from django.db import models
from user_app.models import User
from django.utils import timezone
from django.conf import settings
from django.core.mail import send_mail
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post', null=True)
    image = models.ImageField(upload_to='post/image', blank=True)
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

@receiver(post_save, sender=Post)
def send_notification(sender,instance,created,**kwargs):
    if created:
        subject = "Thought of the day"
        email_from = settings.EMAIL_HOST_USER
        recipient_list = ['jagratirathod02@gmail.com']
        message = f'Hii {instance.user.first_name} {instance.user.last_name} , A New Post Title  "{instance.title}" has been Posted'
        send_mail(subject,message,email_from,recipient_list)
    

class LikePost(models.Model):
    like_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='users', null=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='like', null=True)
    number_of_likes = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)

    
   
class CommentPost(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comment', null=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comment_post', null=True)
    message = models.CharField(max_length=90)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.message 

post_app/post_api/models.py
from django.db import models

# Create your models here.

post_app/forms.py
from django import forms
from .models import Post  ,CommentPost


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'title']



class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = CommentPost
        fields = ['message']

post_app/post_api/views.py
from rest_framework .views import APIView
from rest_framework.response import Response
from rest_framework.generics import ListAPIView , CreateAPIView
from post_app.models import Post , LikePost
from .serializer import PostSerializer , CreatePostSerializer , LikePostSerializer
from django.db.models import Q
from follow_user.models import SendRequest 
from django.utils.timezone import make_aware
from datetime import datetime


# Create your views here.

class CheckPostAPI(APIView):
    def get(self,request):
        return Response("check post api......")

class ListPostView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get_queryset(self):
        start_date = self.request.GET.get("start_date")
        end_date  =  self.request.GET.get("end_date")

        if start_date and end_date:
            start_date = make_aware(datetime.strptime(start_date, "%Y-%m-%d"))
            end_date = make_aware(datetime.strptime(end_date, "%Y-%m-%d"))
            post = Post.objects.filter(user=self.request.user, created_at__range=[start_date, end_date])
            return post
        else:
            senders_post = SendRequest.objects.filter(user=self.request.user, status="Following").values_list('sender')
            users = Post.objects.filter(Q(user=self.request.user) | Q(user__in=senders_post))
            return users


class CreatePostview(CreateAPIView):
    # localhost:8000/api_post/create_post/
    queryset = Post
    serializer_class = CreatePostSerializer

    def perform_create(self, serializer):
        serializer.save(
            user=self.request.user
        )


class LikePostView(APIView):
    def get(self,request):
        post_id  =  self.request.GET.get("post_id")
        post = Post.objects.get(id = post_id)

        like_post = LikePost.objects.filter(post = post , like_by = self.request.user)
        if not like_post:
            LikePost.objects.create(post = post , like_by = self.request.user,number_of_likes = 1)
            return Response("Successfully Like Post")








    





        







          

post_app/views.py
from typing import Any
from django.db.models import Q
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView
from follow_user.models import SendRequest
from django.views import View
from .forms import CreateCommentForm, PostForm
from .models import CommentPost, LikePost, Post
from django.utils.timezone import make_aware
from datetime import datetime
from django.db.models import F
from user_app.models import User
from django.db.models import Sum


# Create your views here.

def home(request):
    return HttpResponse("post testing")

class ListPostView(ListView):
    model = Post
    template_name = "users_post.html"
    context_object_name = "user_post"

    def get_queryset(self):
        start_date = self.request.GET.get("start_date")
        end_date = self.request.GET.get("end_date")
        if start_date and end_date:
            start_date = make_aware(datetime.strptime(start_date, "%Y-%m-%d"))
            end_date = make_aware(datetime.strptime(end_date, "%Y-%m-%d"))
            post = Post.objects.filter(user=self.request.user, created_at__range=[start_date, end_date])
            return post
        else:
            senders_post = SendRequest.objects.filter(user=self.request.user, status="Following").values_list('sender')
            users = Post.objects.filter(Q(user=self.request.user) | Q(user__in=senders_post))
            return users
        
    # def post(self, request, *args, **kwargs):
    #     return self.get(request, *args, **kwargs)

def createpostview(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form = form.save()
            return redirect("post_app:list_post")
        else:
            return HttpResponse("Form is not valid") 
    else:
        form = PostForm()
        return render(request, "post.html", {"form": form})


class LikePostView(View):
    def get(self, request):
        post_id = request.GET.get("post_id")
        post = Post.objects.get(id=post_id)
        like = LikePost.objects.filter(post = post , like_by = request.user)
        if not like:
            LikePost.objects.create(post = post , like_by = request.user,number_of_likes = 1)
            return redirect("post_app:list_post")
        return HttpResponse("Already liked")
    

class CreateCommentView(CreateView):
    form_class = CreateCommentForm
    template_name = "comment.html"
    success_url = reverse_lazy('post_app:list_post')
    success_message = "Successfully  Comment"

    def form_valid(self, form):
        post_id = self.request.GET.get("post_id")
        post_id = Post.objects.get(id=post_id)
        form.instance.user = self.request.user
        form.instance.post = post_id
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.request.GET.get("post_id")
        post_id = Post.objects.get(id=post_id)
        context['post_message'] = CommentPost.objects.filter(post = post_id)
        return context

class PostDelete(DeleteView):
    model = Post
    template_name = "post_delete.html"
    success_url = reverse_lazy("post_app:list_post")


class PostSortView(View):
    def get(self,request):
        sort = request.GET.get('sort')
        like_post =  Post.objects.filter(user=request.user)
        if sort == "LTH":
            user_post = like_post.order_by('like__number_of_likes')
        else:
            user_post = like_post.order_by('-like__number_of_likes')
        return render(request, 'users_post.html', {'user_post': user_post})
    


        

post_app/templates/post.html
{% extends 'f_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div style="background-color: bisque; height:max-content">
<center>

{% if messages %}
{% for message in messages %}
<div>{{ message}}</div>
{% endfor %}
{% endif %}
    

<div style="color:black;">
    <form action="" method="POST" enctype="multipart/form-data" style="width: 300px; height:1000px;" >
        {% csrf_token %}
        <br><br><br>
        <h6><strong>- Post Here -</strong> </h6> <br>
        {{form|crispy}}  <br>
        <button type="submit" class="btn btn-danger">Save</button>
    </form>
</div>

</center>
</div>
{% endblock %}

post_app/templates/post_delete.html
{% extends 'f_base.html' %}

{% block content %}

<div style="background-color:blanchedalmond;height:500px;">
   
    <center><br><br><br><br>

        <form method="POST">
            {% csrf_token %}

            <p>Are you sure you want to delete ?</p>
            {{form}}

            <input type="submit" value="Confirm">
        </form>
    </center>
</div>

{% endblock %}

post_app/templates/users_post.html
{% extends 'f_base.html' %}
{% load like_post %}


{% block content %}
{% if message %}
<div>{{ message}}</div>
{% endif %}
    
 
<a href="{% url 'post_app:create_post' %}" class="btn btn-secondary">Add Post</a> <br><br>

<center>
  <form method="GET" action="{% url 'post_app:list_post' %}">
    <div>
      <label>Start Date</label>
      <input type="text" name="start_date" placeholder="Enter start date">
      <label>End Date</label>
      <input type="text" name="end_date" placeholder="Enter end date">
      <input type="submit" value="Filter">
    </div>
  </form>
</center>  <br><br>

<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-2">All Post</h1>  <hr/>
<div style = "background-color:blanchedalmond; height:max-content"><br><br>

  <table class="table-auto mx-auto w-full mt-8 border-collapse">
      <thead style="background-color:rgb(34, 34, 74); color:white">
        <tr  class="uppercase font-semibold text-sm">
          <th class=" border border-black px-4 py-2">Title</th>
          <th class=" border border-black px-4 py-2">Image</th>
          <th class=" border border-black px-4 py-2"></th>
          <th class=" border border-black px-4 py-2"></th>
          <th class=" border border-black px-4 py-2"></th>
        </tr>
      </thead>

      <tbody>
        {% for post in user_post %}
        <tr style="background-color:rgb(245, 245, 159);color:black;"> 
          <td class="border border-blue-900 px-4 py-2">{{post.title}}</td>
          <td>
            <img class="card-img-top" src="{{post.image.url}}" style="width:260px; height: 150px;"alt="Card image cap">
          </td>

          <td>
            <a href="/post_app/like_post/?post_id={{ post.id }}"><button type="button" class="btn btn-danger">Likes - {{post.id|number_of_likes}}</button>
            </a>
          </td>

          <td>
            <a href="/post_app/comment_post/?post_id={{ post.id }}"><button type="button" class="btn btn-warning">Comments</button></a>
          </td>

          <td>
            <a href="{% url 'post_app:delete_post' post.id %}"><button type="button" class="btn btn-dark">Delete</button></a>
          </td>
          {% endfor %}
       </tbody>
      </table>
</div>
{% endblock %}